### ISSUE TITLE
loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: OpenAPI spec does not exists

### ISSUE THREAD

**Issue by zhaofengcumt** [DirectXMan12/k8s-prometheus-adapter#257] opened 2019-11-12 07:32 UTC
my  kube-api-server version 1.12.6

this is the log of kube-api-server
```
11月 12 15:18:16 wlwk8s11 kube-apiserver[878]: I1112 15:18:16.827915     878 trace.go:76] Trace[1528972388]: "Get /api/v1/namespaces/kube-system/secrets/kubernetes-dashboard-token-8vln9" (started: 2019-11-12 15:18:14.988628925 +0800 
11月 12 15:17:15 wlwk8s11 kube-apiserver[878]: I1112 15:17:15.916763     878 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
**11月 12 15:17:15 wlwk8s11 kube-apiserver[878]: E1112 15:17:15.916740     878 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: OpenAPI spec does not exists
11月 12 15:17:15 wlwk8s11 kube-apiserver[878]: I1112 15:17:15.905733     878 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io**
```

this is my apiservices

```
 kubectl get apiservice
NAME                                    SERVICE                         AVAILABLE   AGE
v1.                                     Local                           True        292d
v1.apps                                 Local                           True        292d
v1.authentication.k8s.io                Local                           True        292d
v1.authorization.k8s.io                 Local                           True        292d
v1.autoscaling                          Local                           True        292d
v1.batch                                Local                           True        292d
v1.monitoring.coreos.com                Local                           True        43d
v1.networking.k8s.io                    Local                           True        292d
v1.rbac.authorization.k8s.io            Local                           True        292d
v1.storage.k8s.io                       Local                           True        292d
v1alpha1.admissionregistration.k8s.io   Local                           True        203d
v1alpha1.rbac.authorization.k8s.io      Local                           True        203d
v1alpha1.scheduling.k8s.io              Local                           True        203d
v1alpha1.settings.k8s.io                Local                           True        203d
v1alpha1.storage.k8s.io                 Local                           True        203d
v1beta1.admissionregistration.k8s.io    Local                           True        292d
v1beta1.apiextensions.k8s.io            Local                           True        292d
v1beta1.apps                            Local                           True        292d
v1beta1.authentication.k8s.io           Local                           True        292d
v1beta1.authorization.k8s.io            Local                           True        292d
v1beta1.batch                           Local                           True        292d
v1beta1.certificates.k8s.io             Local                           True        292d
v1beta1.coordination.k8s.io             Local                           True        203d
v1beta1.events.k8s.io                   Local                           True        292d
v1beta1.extensions                      Local                           True        292d
v1beta1.metrics.k8s.io                  monitoring/prometheus-adapter   True        94d
v1beta1.policy                          Local                           True        292d
v1beta1.rbac.authorization.k8s.io       Local                           True        292d
v1beta1.scheduling.k8s.io               Local                           True        292d
v1beta1.storage.k8s.io                  Local                           True        292d
v1beta2.apps                            Local                           True        292d
v2alpha1.batch                          Local                           True        203d
v2beta1.autoscaling                     Local                           True        292d
v2beta2.autoscaling                     Local                           True        203d
```

**Comment by ivnilv** [comment] 2019-11-28 15:40
Dupe of #254 ?

**Closed** 2020-10-26 08:54 UTC
